build:
  maxIssues: 0

complexity:
  LongParameterList:
    ignoreDefaultParameters: true
    ignoreAnnotated: ['Inject']
  TooManyFunctions:
    ignoreOverridden: true

formatting:
  active: true
  Indentation:
    active: true

